name: Makefile CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
      
    - name: Run build and check
      run: make status build fmt vet test

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.2.0